# Generated by Django 5.2.17 on 2026-09-10 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetentionDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('business_classification', models.CharField(choices=[('POSITIVE_INTENT', 'Positive Intent'), ('BARRIER', 'Barrier / Financial'), ('SERVICE_ISSUE', 'Service Issue'), ('COMPETITOR_LOSS', 'Competitor Loss'), ('SUCCESS', 'Success / Verify Recharge'), ('INVALID', 'Invalid'), ('UNREACHABLE', 'Unreachable'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('default_priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('auto_callback_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField(auto_now_add=True)),
                ('call_time', models.TimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('next_action', models.CharField(choices=[('CALL_AGAIN', 'Call Again'), ('VERIFY_RECHARGE', 'Verify Recharge'), ('ESCALATE_SERVICE', 'Escalate Service Issue'), ('SEND_OFFER', 'Send Offer / Scheme'), ('CONTACT_DEALER', 'Contact Dealer'), ('CLOSE_LOST', 'Close as Lost')], default='CALL_AGAIN', max_length=30)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_time', models.TimeField(blank=True, null=True)),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customers.customer')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='followups.retentiondisposition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='followups.retentioncategory')),
            ],
        ),
        migrations.AddField(
            model_name='retentiondisposition',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='followups.retentionsubcategory'),
        ),
    ]
