# Generated by Django 5.2.17 on 2026-09-11 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customerremark'),
        ('followups', '0002_call_datetime_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerfollowup',
            index=models.Index(fields=['customer', '-created_at'], name='followups_c_custome_4e12c2_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfollowup',
            index=models.Index(fields=['agent', 'call_date'], name='followups_c_agent_i_9105a5_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfollowup',
            index=models.Index(fields=['call_date'], name='followups_c_call_da_b3f38c_idx'),
        ),
    ]
