# Generated by Django 5.2.17 on 2026-09-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0003_customerfollowup_followups_c_custome_4e12c2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfollowup',
            name='next_action',
            field=models.CharField(choices=[('CALL_AGAIN', 'Call Again'), ('NO_CALL_NEEDED', 'No Need to Call Again')], default='CALL_AGAIN', max_length=30),
        ),
    ]
