from .models import BusinessClassification, PriorityLevel


RETENTION_CONFIG = {
    'Churn Follow Up': [
        ('Call not receive, connected', BusinessClassification.UNREACHABLE, PriorityLevel.LOW, 1),
        ('Router already collected - not at customer site.', BusinessClassification.BARRIER, PriorityLevel.LOW, 0),
        ('Customer is out of home', BusinessClassification.UNREACHABLE, PriorityLevel.LOW, 2),
        ('Due to exam', BusinessClassification.BARRIER, PriorityLevel.MEDIUM, 7),
        ('Untag Issue', BusinessClassification.SERVICE_ISSUE, PriorityLevel.MEDIUM, 2),
        ('Will recharge after 7 days', BusinessClassification.POSITIVE_INTENT, PriorityLevel.MEDIUM, 7),
        ('Multiple Connection of Dishhome Internet', BusinessClassification.BARRIER, PriorityLevel.LOW, 0),
        ('Non fibernet User (Invalid KYC)', BusinessClassification.INVALID, PriorityLevel.LOW, 0),
        ('Other Isp using (12M plan)', BusinessClassification.COMPETITOR_LOSS, PriorityLevel.LOW, 0),
        ('Router Collected By Dealer', BusinessClassification.BARRIER, PriorityLevel.LOW, 0),
        ('Denied due to bad service', BusinessClassification.SERVICE_ISSUE, PriorityLevel.HIGH, 1),
        ('Financial Issue', BusinessClassification.BARRIER, PriorityLevel.MEDIUM, 7),
        ('Already Recharged', BusinessClassification.SUCCESS, PriorityLevel.CRITICAL, 0),
        ('Denied due to late service', BusinessClassification.SERVICE_ISSUE, PriorityLevel.HIGH, 1),
        ('Denied due to drop wire charge policy', BusinessClassification.SERVICE_ISSUE, PriorityLevel.HIGH, 2),
        ('Interested will recharge soon', BusinessClassification.POSITIVE_INTENT, PriorityLevel.HIGH, 2),
        ('Ready To recharge today', BusinessClassification.POSITIVE_INTENT, PriorityLevel.CRITICAL, 0),
        ('Interested callback required', BusinessClassification.POSITIVE_INTENT, PriorityLevel.HIGH, 0),
        ('Process for router refund', BusinessClassification.SERVICE_ISSUE, PriorityLevel.LOW, 5),
        ('Upgrade / Downgrade request', BusinessClassification.POSITIVE_INTENT, PriorityLevel.HIGH, 1),
        ('Other Isp using (6M plan)', BusinessClassification.COMPETITOR_LOSS, PriorityLevel.LOW, 0),
        ('Customer denied due to higher pricing than other ISPs', BusinessClassification.COMPETITOR_LOSS, PriorityLevel.MEDIUM, 3),
        ('Customer wants additional offer', BusinessClassification.POSITIVE_INTENT, PriorityLevel.HIGH, 1),
        ('Busy Need to call back later', BusinessClassification.UNREACHABLE, PriorityLevel.MEDIUM, 0),
        ('Ready To recharge within 3 days', BusinessClassification.POSITIVE_INTENT, PriorityLevel.HIGH, 3),
        ('Ready To recharge within 7 days', BusinessClassification.POSITIVE_INTENT, PriorityLevel.MEDIUM, 7),
        ('Will confirm later', BusinessClassification.POSITIVE_INTENT, PriorityLevel.MEDIUM, 3),
    ],
    'Pre Disconnection Follow Up': [
        ('Call not receive, connected', BusinessClassification.UNREACHABLE, PriorityLevel.LOW, 1),
        ('Customer is out of home', BusinessClassification.UNREACHABLE, PriorityLevel.LOW, 2),
        ('Due to exam', BusinessClassification.BARRIER, PriorityLevel.MEDIUM, 7),
        ('Untag Issue', BusinessClassification.SERVICE_ISSUE, PriorityLevel.MEDIUM, 2),
        ('Denied due to late service', BusinessClassification.SERVICE_ISSUE, PriorityLevel.HIGH, 1),
        ('Denied due to bad service', BusinessClassification.SERVICE_ISSUE, PriorityLevel.HIGH, 1),
        ('Denied due to drop wire charge policy', BusinessClassification.SERVICE_ISSUE, PriorityLevel.HIGH, 2),
        ('Non fibernet User (Invalid KYC)', BusinessClassification.INVALID, PriorityLevel.LOW, 0),
        ('Multiple Connection of Dishhome Internet', BusinessClassification.BARRIER, PriorityLevel.LOW, 0),
        ('Financial Issue', BusinessClassification.BARRIER, PriorityLevel.MEDIUM, 7),
        ('Ready To recharge today', BusinessClassification.POSITIVE_INTENT, PriorityLevel.CRITICAL, 0),
        ('Will recharge after 7 days', BusinessClassification.POSITIVE_INTENT, PriorityLevel.MEDIUM, 7),
        ('Interested callback required', BusinessClassification.POSITIVE_INTENT, PriorityLevel.HIGH, 0),
        ('Interested will recharge soon', BusinessClassification.POSITIVE_INTENT, PriorityLevel.HIGH, 2),
        ('Upgrade/Downgrade request', BusinessClassification.POSITIVE_INTENT, PriorityLevel.HIGH, 1),
        ('Customer denied due to higher pricing than other ISPs', BusinessClassification.COMPETITOR_LOSS, PriorityLevel.MEDIUM, 3),
        ('Busy Need to call back later', BusinessClassification.UNREACHABLE, PriorityLevel.MEDIUM, 0),
        ('Already Recharged', BusinessClassification.SUCCESS, PriorityLevel.CRITICAL, 0),
        ('Will confirm later', BusinessClassification.POSITIVE_INTENT, PriorityLevel.MEDIUM, 3),
        ('Will contact dealer', BusinessClassification.POSITIVE_INTENT, PriorityLevel.MEDIUM, 3),
        ('Customer wants additional offer', BusinessClassification.POSITIVE_INTENT, PriorityLevel.HIGH, 1),
        ('Ready To recharge within 3 days', BusinessClassification.POSITIVE_INTENT, PriorityLevel.HIGH, 3),
        ('Ready To recharge within 7 days', BusinessClassification.POSITIVE_INTENT, PriorityLevel.MEDIUM, 7),
    ],
    'Dealer Follow Up': [
        ('Call not receive, connected', BusinessClassification.UNREACHABLE, PriorityLevel.LOW, 1),
        ('No Response', BusinessClassification.UNREACHABLE, PriorityLevel.LOW, 1),
        ('Informed about Scheme and target', BusinessClassification.POSITIVE_INTENT, PriorityLevel.MEDIUM, 2),
        ('Inactive Sub-Dealer', BusinessClassification.OTHER, PriorityLevel.LOW, 0),
        ('Informed about Recharge request', BusinessClassification.POSITIVE_INTENT, PriorityLevel.MEDIUM, 2),
        ('Invalid Number', BusinessClassification.INVALID, PriorityLevel.LOW, 0),
        ('Insufficient fund will recharge soon', BusinessClassification.POSITIVE_INTENT, PriorityLevel.MEDIUM, 3),
        ('Customer suggest to router refund', BusinessClassification.SERVICE_ISSUE, PriorityLevel.LOW, 5),
        ('Denied due to late service', BusinessClassification.SERVICE_ISSUE, PriorityLevel.HIGH, 1),
        ('Denied due to bad service', BusinessClassification.SERVICE_ISSUE, PriorityLevel.HIGH, 1),
    ],
}
