# Generated by Django 5.2.17 on 2026-09-10 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('disposition_name', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('new_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignments', to=settings.AUTH_USER_MODEL)),
                ('previous_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(db_index=True, max_length=20)),
                ('alternate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('area_location', models.CharField(blank=True, max_length=100, null=True)),
                ('package', models.CharField(max_length=100)),
                ('current_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_recharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_recharge_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('days_since_churn', models.IntegerField(default=0)),
                ('churn_bucket', models.CharField(choices=[('0-30', '0-30 Days'), ('31-60', '31-60 Days'), ('61-90', '61-90 Days'), ('90+', '90+ Days')], default='0-30', max_length=20)),
                ('customer_status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('NOT_CONTACTED', 'Not Contacted'), ('FOLLOWUP_PENDING', 'Follow-up Pending'), ('CONTACTED', 'Contacted'), ('POSITIVE_INTENT', 'Positive Intent'), ('READY_TO_RECHARGE', 'Ready to Recharge'), ('RECHARGED', 'Recharged'), ('LOST', 'Lost'), ('INVALID', 'Invalid'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=30)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, default='MEDIUM', max_length=20)),
                ('assignment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, db_index=True, null=True)),
                ('next_followup_time', models.TimeField(blank=True, null=True)),
                ('latest_note', models.TextField(blank=True, null=True)),
                ('recharge_status', models.CharField(choices=[('PENDING', 'Pending'), ('READY_TODAY', 'Ready Today'), ('RECHARGED', 'Recharged'), ('NOT_RECHARGED', 'Not Recharged')], db_index=True, default='PENDING', max_length=20)),
                ('recharge_date', models.DateField(blank=True, db_index=True, null=True)),
                ('recharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recovered_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_customers', to=settings.AUTH_USER_MODEL)),
                ('assigned_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_customers', to=settings.AUTH_USER_MODEL)),
                ('assigned_team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_lead_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
